services:
  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"

  nifi-node1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nifi-node1
    ports:
      - "${NIFI_PORT_HTTP}:8080"
    environment:
      NIFI_WEB_HTTP_PORT: 8080
      NIFI_CLUSTER_IS_NODE: 'false'
      NIFI_CLUSTER_NODE_PROTOCOL_PORT: 8082
      NIFI_CLUSTER_NODE_ADDRESS: nifi-node1
      NIFI_ZK_CONNECT_STRING: 'zookeeper:2181'
      NIFI_ELECTION_MAX_WAIT: '1 min'
      NIFI_SENSITIVE_PROPS_KEY: 'MySuperSecretKey123'
      INPUT_FOLDER: ${INPUT_FOLDER}
      OUTPUT_FOLDER: ${OUTPUT_FOLDER}
      SCRIPTS_FOLDER: ${SCRIPTS_FOLDER}
      KAFKA_BROKER: ${KAFKA_BROKER}
    volumes:
      - ${INPUT_FOLDER}:${INPUT_FOLDER}
      - ${OUTPUT_FOLDER}:${OUTPUT_FOLDER}
      - ${LOGS_FOLDER}/node1:/opt/nifi/nifi-current/logs
      - ${SCRIPTS_FOLDER}:${SCRIPTS_FOLDER}
      - ./conf1:/opt/nifi/nifi-current/conf
    depends_on:
      - zookeeper

